# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _CoreClient3
else:
    import _CoreClient3

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _CoreClient3.SHARED_PTR_DISOWN
class doubleArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _CoreClient3.doubleArray_swiginit(self, _CoreClient3.new_doubleArray(nelements))
    __swig_destroy__ = _CoreClient3.delete_doubleArray

    def __getitem__(self, index):
        return _CoreClient3.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _CoreClient3.doubleArray___setitem__(self, index, value)

    def cast(self):
        return _CoreClient3.doubleArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _CoreClient3.doubleArray_frompointer(t)

# Register doubleArray in _CoreClient3:
_CoreClient3.doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(t):
    return _CoreClient3.doubleArray_frompointer(t)

class ICGClient(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def CreateCGClient():
        return _CoreClient3.ICGClient_CreateCGClient()

    def Destroy(self):
        return _CoreClient3.ICGClient_Destroy(self)

    def Connect(self, *args):
        return _CoreClient3.ICGClient_Connect(self, *args)

    def ReceiveMulticastData(self, i_MulticastIPAddress, i_LocalIPAddress, i_Port):
        return _CoreClient3.ICGClient_ReceiveMulticastData(self, i_MulticastIPAddress, i_LocalIPAddress, i_Port)

    def StopReceivingMulticastData(self):
        return _CoreClient3.ICGClient_StopReceivingMulticastData(self)

    def IsConnected(self):
        return _CoreClient3.ICGClient_IsConnected(self)

    def IsMulticastReceiving(self):
        return _CoreClient3.ICGClient_IsMulticastReceiving(self)

    def SetRequestTypes(self, i_RequestedType, i_bEnable=True):
        return _CoreClient3.ICGClient_SetRequestTypes(self, i_RequestedType, i_bEnable)

    def SetBufferSize(self, i_MaxFrames):
        return _CoreClient3.ICGClient_SetBufferSize(self, i_MaxFrames)

    def SetDecodeVideo(self, i_bDecode):
        return _CoreClient3.ICGClient_SetDecodeVideo(self, i_bDecode)

    def SetStreamMode(self, i_bStream):
        return _CoreClient3.ICGClient_SetStreamMode(self, i_bStream)

    def SetApexDeviceFeedback(self, i_DeviceID, i_bOn):
        return _CoreClient3.ICGClient_SetApexDeviceFeedback(self, i_DeviceID, i_bOn)

    def SetFilter(self, i_rFilter):
        return _CoreClient3.ICGClient_SetFilter(self, i_rFilter)

    def SendPing(self):
        return _CoreClient3.ICGClient_SendPing(self)

    def RequestFrame(self):
        return _CoreClient3.ICGClient_RequestFrame(self)

    def RequestNextFrame(self):
        return _CoreClient3.ICGClient_RequestNextFrame(self)

    def ClearBuffer(self):
        return _CoreClient3.ICGClient_ClearBuffer(self)

    def SetServerToTransmitMulticast(self, i_MulticastIPAddress, i_ServerIPAddress, i_Port):
        return _CoreClient3.ICGClient_SetServerToTransmitMulticast(self, i_MulticastIPAddress, i_ServerIPAddress, i_Port)

    def StopMulticastTransmission(self):
        return _CoreClient3.ICGClient_StopMulticastTransmission(self)

    def IsMulticastController(self):
        return _CoreClient3.ICGClient_IsMulticastController(self)

    def PollFrame(self, o_rFrame):
        return _CoreClient3.ICGClient_PollFrame(self, o_rFrame)

    def PollFrames(self, o_rFrames):
        return _CoreClient3.ICGClient_PollFrames(self, o_rFrames)

    def WaitFrame(self, o_rFrame, i_TimeoutMs):
        return _CoreClient3.ICGClient_WaitFrame(self, o_rFrame, i_TimeoutMs)

    def WaitFrames(self, o_rFrames, i_TimeoutMs):
        return _CoreClient3.ICGClient_WaitFrames(self, o_rFrames, i_TimeoutMs)

    def SetLogFile(self, i_rLog):
        return _CoreClient3.ICGClient_SetLogFile(self, i_rLog)
    __swig_destroy__ = _CoreClient3.delete_ICGClient

# Register ICGClient in _CoreClient3:
_CoreClient3.ICGClient_swigregister(ICGClient)

def ICGClient_CreateCGClient():
    return _CoreClient3.ICGClient_CreateCGClient()

Up = _CoreClient3.Up
Down = _CoreClient3.Down
Left = _CoreClient3.Left
Right = _CoreClient3.Right
Forward = _CoreClient3.Forward
Backward = _CoreClient3.Backward
ServerOrientationUnknown = _CoreClient3.ServerOrientationUnknown
YUp = _CoreClient3.YUp
ZUp = _CoreClient3.ZUp
AxisMappingResultSuccess = _CoreClient3.AxisMappingResultSuccess
AxisMappingResultCoLinearAxes = _CoreClient3.AxisMappingResultCoLinearAxes
AxisMappingResultLeftHandedAxes = _CoreClient3.AxisMappingResultLeftHandedAxes
ClientPull = _CoreClient3.ClientPull
ClientPullPreFetch = _CoreClient3.ClientPullPreFetch
ServerPush = _CoreClient3.ServerPush
TimecodeStandardNone = _CoreClient3.TimecodeStandardNone
PAL = _CoreClient3.PAL
NTSC = _CoreClient3.NTSC
NTSCDrop = _CoreClient3.NTSCDrop
Film = _CoreClient3.Film
NTSCFilm = _CoreClient3.NTSCFilm
ATSC = _CoreClient3.ATSC
DeviceTypeUnknown = _CoreClient3.DeviceTypeUnknown
ForcePlate = _CoreClient3.ForcePlate
EyeTracker = _CoreClient3.EyeTracker
UnitUnknown = _CoreClient3.UnitUnknown
Volt = _CoreClient3.Volt
Newton = _CoreClient3.Newton
NewtonMeter = _CoreClient3.NewtonMeter
Meter = _CoreClient3.Meter
Kilogram = _CoreClient3.Kilogram
Second = _CoreClient3.Second
Ampere = _CoreClient3.Ampere
Kelvin = _CoreClient3.Kelvin
Mole = _CoreClient3.Mole
Candela = _CoreClient3.Candela
Radian = _CoreClient3.Radian
Steradian = _CoreClient3.Steradian
MeterSquared = _CoreClient3.MeterSquared
MeterCubed = _CoreClient3.MeterCubed
MeterPerSecond = _CoreClient3.MeterPerSecond
MeterPerSecondSquared = _CoreClient3.MeterPerSecondSquared
RadianPerSecond = _CoreClient3.RadianPerSecond
RadianPerSecondSquared = _CoreClient3.RadianPerSecondSquared
Hertz = _CoreClient3.Hertz
Joule = _CoreClient3.Joule
Watt = _CoreClient3.Watt
Pascal = _CoreClient3.Pascal
Lumen = _CoreClient3.Lumen
Lux = _CoreClient3.Lux
Coulomb = _CoreClient3.Coulomb
Ohm = _CoreClient3.Ohm
Farad = _CoreClient3.Farad
Weber = _CoreClient3.Weber
Tesla = _CoreClient3.Tesla
Henry = _CoreClient3.Henry
Siemens = _CoreClient3.Siemens
Becquerel = _CoreClient3.Becquerel
Gray = _CoreClient3.Gray
Sievert = _CoreClient3.Sievert
Katal = _CoreClient3.Katal
Unknown = _CoreClient3.Unknown
NotImplemented = _CoreClient3.NotImplemented
Success = _CoreClient3.Success
InvalidHostName = _CoreClient3.InvalidHostName
InvalidMulticastIP = _CoreClient3.InvalidMulticastIP
NullClient = _CoreClient3.NullClient
ClientAlreadyConnected = _CoreClient3.ClientAlreadyConnected
ClientConnectionFailed = _CoreClient3.ClientConnectionFailed
ServerAlreadyTransmittingMulticast = _CoreClient3.ServerAlreadyTransmittingMulticast
ServerNotTransmittingMulticast = _CoreClient3.ServerNotTransmittingMulticast
NotConnected = _CoreClient3.NotConnected
NoFrame = _CoreClient3.NoFrame
InvalidIndex = _CoreClient3.InvalidIndex
InvalidCameraName = _CoreClient3.InvalidCameraName
InvalidSubjectName = _CoreClient3.InvalidSubjectName
InvalidSegmentName = _CoreClient3.InvalidSegmentName
InvalidMarkerName = _CoreClient3.InvalidMarkerName
InvalidDeviceName = _CoreClient3.InvalidDeviceName
InvalidDeviceOutputName = _CoreClient3.InvalidDeviceOutputName
InvalidLatencySampleName = _CoreClient3.InvalidLatencySampleName
InvalidFrameRateName = _CoreClient3.InvalidFrameRateName
CoLinearAxes = _CoreClient3.CoLinearAxes
LeftHandedAxes = _CoreClient3.LeftHandedAxes
HapticAlreadySet = _CoreClient3.HapticAlreadySet
EarlyDataRequested = _CoreClient3.EarlyDataRequested
LateDataRequested = _CoreClient3.LateDataRequested
InvalidOperation = _CoreClient3.InvalidOperation
NotSupported = _CoreClient3.NotSupported
ConfigurationFailed = _CoreClient3.ConfigurationFailed
NotPresent = _CoreClient3.NotPresent
class VClient(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        _CoreClient3.VClient_swiginit(self, _CoreClient3.new_VClient())
    __swig_destroy__ = _CoreClient3.delete_VClient

    def GetVersion(self):
        return _CoreClient3.VClient_GetVersion(self)

    def Connect(self, i_pClient, i_rHostName):
        return _CoreClient3.VClient_Connect(self, i_pClient, i_rHostName)

    def ConnectToMulticast(self, i_pClient, i_rLocalIP, i_rMulticastIP):
        return _CoreClient3.VClient_ConnectToMulticast(self, i_pClient, i_rLocalIP, i_rMulticastIP)

    def Disconnect(self):
        return _CoreClient3.VClient_Disconnect(self)

    def StartTransmittingMulticast(self, i_rServerIP, i_rMulticastIP):
        return _CoreClient3.VClient_StartTransmittingMulticast(self, i_rServerIP, i_rMulticastIP)

    def StopTransmittingMulticast(self):
        return _CoreClient3.VClient_StopTransmittingMulticast(self)

    def IsConnected(self):
        return _CoreClient3.VClient_IsConnected(self)

    def SetBufferSize(self, i_MaxFrames):
        return _CoreClient3.VClient_SetBufferSize(self, i_MaxFrames)

    def GetFrame(self):
        return _CoreClient3.VClient_GetFrame(self)

    def GetFrameNumber(self):
        return _CoreClient3.VClient_GetFrameNumber(self)

    def GetFrameRate(self):
        return _CoreClient3.VClient_GetFrameRate(self)

    def GetTimecode(self):
        return _CoreClient3.VClient_GetTimecode(self)

    def GetLatencyTotal(self):
        return _CoreClient3.VClient_GetLatencyTotal(self)

    def GetLatencySampleCount(self):
        return _CoreClient3.VClient_GetLatencySampleCount(self)

    def GetLatencySampleName(self, i_SampleIndex):
        return _CoreClient3.VClient_GetLatencySampleName(self, i_SampleIndex)

    def GetLatencySampleValue(self, i_rSampleName):
        return _CoreClient3.VClient_GetLatencySampleValue(self, i_rSampleName)

    def GetHardwareFrameNumber(self):
        return _CoreClient3.VClient_GetHardwareFrameNumber(self)

    def GetFrameRateCount(self):
        return _CoreClient3.VClient_GetFrameRateCount(self)

    def GetFrameRateName(self, i_FrameRateIndex):
        return _CoreClient3.VClient_GetFrameRateName(self, i_FrameRateIndex)

    def GetFrameRateValue(self, i_rFrameRateName):
        return _CoreClient3.VClient_GetFrameRateValue(self, i_rFrameRateName)

    def SetSegmentDataEnabled(self, i_i_bEnabled):
        return _CoreClient3.VClient_SetSegmentDataEnabled(self, i_i_bEnabled)

    def SetLightweightSegmentDataEnabled(self, i_i_bEnabled):
        return _CoreClient3.VClient_SetLightweightSegmentDataEnabled(self, i_i_bEnabled)

    def SetMarkerDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetMarkerDataEnabled(self, i_bEnabled)

    def SetUnlabeledMarkerDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetUnlabeledMarkerDataEnabled(self, i_bEnabled)

    def SetMarkerRayDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetMarkerRayDataEnabled(self, i_bEnabled)

    def SetDeviceDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetDeviceDataEnabled(self, i_bEnabled)

    def SetCentroidDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetCentroidDataEnabled(self, i_bEnabled)

    def SetGreyscaleDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetGreyscaleDataEnabled(self, i_bEnabled)

    def SetDebugDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetDebugDataEnabled(self, i_bEnabled)

    def SetCameraWand2dDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetCameraWand2dDataEnabled(self, i_bEnabled)

    def SetVideoDataEnabled(self, i_bEnabled):
        return _CoreClient3.VClient_SetVideoDataEnabled(self, i_bEnabled)

    def EnableSegmentData(self):
        return _CoreClient3.VClient_EnableSegmentData(self)

    def EnableLightweightSegmentData(self):
        return _CoreClient3.VClient_EnableLightweightSegmentData(self)

    def EnableMarkerData(self):
        return _CoreClient3.VClient_EnableMarkerData(self)

    def EnableUnlabeledMarkerData(self):
        return _CoreClient3.VClient_EnableUnlabeledMarkerData(self)

    def EnableMarkerRayData(self):
        return _CoreClient3.VClient_EnableMarkerRayData(self)

    def EnableDeviceData(self):
        return _CoreClient3.VClient_EnableDeviceData(self)

    def EnableCentroidData(self):
        return _CoreClient3.VClient_EnableCentroidData(self)

    def EnableGreyscaleData(self):
        return _CoreClient3.VClient_EnableGreyscaleData(self)

    def EnableDebugData(self):
        return _CoreClient3.VClient_EnableDebugData(self)

    def EnableCameraWand2dData(self):
        return _CoreClient3.VClient_EnableCameraWand2dData(self)

    def EnableVideoData(self):
        return _CoreClient3.VClient_EnableVideoData(self)

    def DisableSegmentData(self):
        return _CoreClient3.VClient_DisableSegmentData(self)

    def DisableLightweightSegmentData(self):
        return _CoreClient3.VClient_DisableLightweightSegmentData(self)

    def DisableMarkerData(self):
        return _CoreClient3.VClient_DisableMarkerData(self)

    def DisableUnlabeledMarkerData(self):
        return _CoreClient3.VClient_DisableUnlabeledMarkerData(self)

    def DisableMarkerRayData(self):
        return _CoreClient3.VClient_DisableMarkerRayData(self)

    def DisableDeviceData(self):
        return _CoreClient3.VClient_DisableDeviceData(self)

    def DisableCentroidData(self):
        return _CoreClient3.VClient_DisableCentroidData(self)

    def DisableGreyscaleData(self):
        return _CoreClient3.VClient_DisableGreyscaleData(self)

    def DisableDebugData(self):
        return _CoreClient3.VClient_DisableDebugData(self)

    def DisableCameraWand2dData(self):
        return _CoreClient3.VClient_DisableCameraWand2dData(self)

    def DisableVideoData(self):
        return _CoreClient3.VClient_DisableVideoData(self)

    def IsSegmentDataEnabled(self):
        return _CoreClient3.VClient_IsSegmentDataEnabled(self)

    def IsLightweightSegmentDataEnabled(self):
        return _CoreClient3.VClient_IsLightweightSegmentDataEnabled(self)

    def IsMarkerDataEnabled(self):
        return _CoreClient3.VClient_IsMarkerDataEnabled(self)

    def IsUnlabeledMarkerDataEnabled(self):
        return _CoreClient3.VClient_IsUnlabeledMarkerDataEnabled(self)

    def IsMarkerRayDataEnabled(self):
        return _CoreClient3.VClient_IsMarkerRayDataEnabled(self)

    def IsDeviceDataEnabled(self):
        return _CoreClient3.VClient_IsDeviceDataEnabled(self)

    def IsCentroidDataEnabled(self):
        return _CoreClient3.VClient_IsCentroidDataEnabled(self)

    def IsGreyscaleDataEnabled(self):
        return _CoreClient3.VClient_IsGreyscaleDataEnabled(self)

    def IsDebugDataEnabled(self):
        return _CoreClient3.VClient_IsDebugDataEnabled(self)

    def IsCameraWand2dDataEnabled(self):
        return _CoreClient3.VClient_IsCameraWand2dDataEnabled(self)

    def IsVideoDataEnabled(self):
        return _CoreClient3.VClient_IsVideoDataEnabled(self)

    def SetStreamMode(self, i_Mode):
        return _CoreClient3.VClient_SetStreamMode(self, i_Mode)

    def SetApexDeviceFeedback(self, i_rDeviceName, i_bOn):
        return _CoreClient3.VClient_SetApexDeviceFeedback(self, i_rDeviceName, i_bOn)

    def SetAxisMapping(self, i_XAxis, i_YAxis, i_ZAxis):
        return _CoreClient3.VClient_SetAxisMapping(self, i_XAxis, i_YAxis, i_ZAxis)

    def GetAxisMapping(self):
        return _CoreClient3.VClient_GetAxisMapping(self)

    def GetServerOrientation(self):
        return _CoreClient3.VClient_GetServerOrientation(self)

    def GetSubjectCount(self):
        return _CoreClient3.VClient_GetSubjectCount(self)

    def GetSubjectName(self, i_SubjectIndex):
        return _CoreClient3.VClient_GetSubjectName(self, i_SubjectIndex)

    def GetSubjectRootSegmentName(self, i_rSubjectName):
        return _CoreClient3.VClient_GetSubjectRootSegmentName(self, i_rSubjectName)

    def GetSegmentCount(self, i_rSubjectName):
        return _CoreClient3.VClient_GetSegmentCount(self, i_rSubjectName)

    def GetSegmentName(self, i_rSubjectName, i_SegmentIndex):
        return _CoreClient3.VClient_GetSegmentName(self, i_rSubjectName, i_SegmentIndex)

    def GetSegmentChildCount(self, i_rSubjectName, i_rSegmentName):
        return _CoreClient3.VClient_GetSegmentChildCount(self, i_rSubjectName, i_rSegmentName)

    def GetSegmentChildName(self, i_rSubjectName, i_rSegmentName, i_SegmentIndex):
        return _CoreClient3.VClient_GetSegmentChildName(self, i_rSubjectName, i_rSegmentName, i_SegmentIndex)

    def GetSegmentParentName(self, i_rSubjectName, i_rSegmentName):
        return _CoreClient3.VClient_GetSegmentParentName(self, i_rSubjectName, i_rSegmentName)

    def GetSegmentStaticTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentStaticTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentStaticRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentStaticRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentStaticRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation):
        return _CoreClient3.VClient_GetSegmentStaticRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation)

    def GetSegmentStaticRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector):
        return _CoreClient3.VClient_GetSegmentStaticRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector)

    def GetSegmentStaticRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentStaticRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentStaticScale(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentStaticScale(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentGlobalTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentGlobalTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentGlobalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentGlobalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentGlobalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation):
        return _CoreClient3.VClient_GetSegmentGlobalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation)

    def GetSegmentGlobalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector):
        return _CoreClient3.VClient_GetSegmentGlobalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector)

    def GetSegmentGlobalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VClient_GetSegmentGlobalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentLocalTranslation(self, i_rSubjectName, i_rSegmentName, o_pThreeVector):
        return _CoreClient3.VClient_GetSegmentLocalTranslation(self, i_rSubjectName, i_rSegmentName, o_pThreeVector)

    def GetSegmentLocalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_pThreeVector):
        return _CoreClient3.VClient_GetSegmentLocalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_pThreeVector)

    def GetSegmentLocalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation):
        return _CoreClient3.VClient_GetSegmentLocalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation)

    def GetSegmentLocalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_pFourVector):
        return _CoreClient3.VClient_GetSegmentLocalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_pFourVector)

    def GetSegmentLocalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_pThreeVector):
        return _CoreClient3.VClient_GetSegmentLocalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_pThreeVector)

    def GetObjectQuality(self, i_rObjectName):
        return _CoreClient3.VClient_GetObjectQuality(self, i_rObjectName)

    def GetMarkerCount(self, i_rSubjectName):
        return _CoreClient3.VClient_GetMarkerCount(self, i_rSubjectName)

    def GetMarkerName(self, i_rSubjectName, i_MarkerIndex):
        return _CoreClient3.VClient_GetMarkerName(self, i_rSubjectName, i_MarkerIndex)

    def GetMarkerParentName(self, i_rSubjectName, i_rMarkerName):
        return _CoreClient3.VClient_GetMarkerParentName(self, i_rSubjectName, i_rMarkerName)

    def GetMarkerGlobalTranslation(self, i_rSubjectName, i_rMarkerName, o_rThreeVector):
        return _CoreClient3.VClient_GetMarkerGlobalTranslation(self, i_rSubjectName, i_rMarkerName, o_rThreeVector)

    def GetMarkerRayAssignmentCount(self, i_rSubjectName, i_rMarkerName):
        return _CoreClient3.VClient_GetMarkerRayAssignmentCount(self, i_rSubjectName, i_rMarkerName)

    def GetMarkerRayAssignment(self, i_rSubjectName, i_rMarkerName, i_rAssignmentIndex):
        return _CoreClient3.VClient_GetMarkerRayAssignment(self, i_rSubjectName, i_rMarkerName, i_rAssignmentIndex)

    def GetUnlabeledMarkerCount(self):
        return _CoreClient3.VClient_GetUnlabeledMarkerCount(self)

    def GetUnlabeledMarkerGlobalTranslation(self, i_MarkerIndex, o_rTranslation):
        return _CoreClient3.VClient_GetUnlabeledMarkerGlobalTranslation(self, i_MarkerIndex, o_rTranslation)

    def GetLabeledMarkerCount(self):
        return _CoreClient3.VClient_GetLabeledMarkerCount(self)

    def GetLabeledMarkerGlobalTranslation(self, i_MarkerIndex, o_rTranslation):
        return _CoreClient3.VClient_GetLabeledMarkerGlobalTranslation(self, i_MarkerIndex, o_rTranslation)

    def GetDeviceCount(self):
        return _CoreClient3.VClient_GetDeviceCount(self)

    def GetDeviceName(self, i_DeviceIndex):
        return _CoreClient3.VClient_GetDeviceName(self, i_DeviceIndex)

    def GetDeviceOutputCount(self, i_rDeviceName):
        return _CoreClient3.VClient_GetDeviceOutputCount(self, i_rDeviceName)

    def GetDeviceOutputName(self, i_rDeviceName, i_DeviceOutputIndex):
        return _CoreClient3.VClient_GetDeviceOutputName(self, i_rDeviceName, i_DeviceOutputIndex)

    def GetDeviceOutputNameComponent(self, i_rDeviceName, i_DeviceOutputIndex):
        return _CoreClient3.VClient_GetDeviceOutputNameComponent(self, i_rDeviceName, i_DeviceOutputIndex)

    def GetDeviceOutputSubsamples(self, *args):
        return _CoreClient3.VClient_GetDeviceOutputSubsamples(self, *args)

    def GetDeviceOutputValue(self, *args):
        return _CoreClient3.VClient_GetDeviceOutputValue(self, *args)

    def GetForcePlateCount(self):
        return _CoreClient3.VClient_GetForcePlateCount(self)

    def GetForcePlateID(self, i_ZeroIndexedPlateIndex):
        return _CoreClient3.VClient_GetForcePlateID(self, i_ZeroIndexedPlateIndex)

    def GetForceVector(self, i_PlateID, o_rForceVector):
        return _CoreClient3.VClient_GetForceVector(self, i_PlateID, o_rForceVector)

    def GetMomentVector(self, i_PlateID, o_rMomentVector):
        return _CoreClient3.VClient_GetMomentVector(self, i_PlateID, o_rMomentVector)

    def GetCentreOfPressure(self, i_PlateID, o_rLocation):
        return _CoreClient3.VClient_GetCentreOfPressure(self, i_PlateID, o_rLocation)

    def GetGlobalForceVector(self, i_PlateID, o_rForceVector):
        return _CoreClient3.VClient_GetGlobalForceVector(self, i_PlateID, o_rForceVector)

    def GetGlobalMomentVector(self, i_PlateID, o_rMomentVector):
        return _CoreClient3.VClient_GetGlobalMomentVector(self, i_PlateID, o_rMomentVector)

    def GetGlobalCentreOfPressure(self, i_PlateID, o_rLocation):
        return _CoreClient3.VClient_GetGlobalCentreOfPressure(self, i_PlateID, o_rLocation)

    def GetForcePlateSubsamples(self, i_PlateID):
        return _CoreClient3.VClient_GetForcePlateSubsamples(self, i_PlateID)

    def GetForceVectorAtSample(self, i_PlateID, i_Subsample, o_rForceVector):
        return _CoreClient3.VClient_GetForceVectorAtSample(self, i_PlateID, i_Subsample, o_rForceVector)

    def GetMomentVectorAtSample(self, i_PlateID, i_Subsample, o_rMomentVector):
        return _CoreClient3.VClient_GetMomentVectorAtSample(self, i_PlateID, i_Subsample, o_rMomentVector)

    def GetCentreOfPressureAtSample(self, i_PlateID, i_Subsample, o_rLocation):
        return _CoreClient3.VClient_GetCentreOfPressureAtSample(self, i_PlateID, i_Subsample, o_rLocation)

    def GetGlobalForceVectorAtSample(self, i_PlateID, i_Subsample, o_rForceVector):
        return _CoreClient3.VClient_GetGlobalForceVectorAtSample(self, i_PlateID, i_Subsample, o_rForceVector)

    def GetGlobalMomentVectorAtSample(self, i_PlateID, i_Subsample, o_rMomentVector):
        return _CoreClient3.VClient_GetGlobalMomentVectorAtSample(self, i_PlateID, i_Subsample, o_rMomentVector)

    def GetGlobalCentreOfPressureAtSample(self, i_PlateID, i_Subsample, o_rLocation):
        return _CoreClient3.VClient_GetGlobalCentreOfPressureAtSample(self, i_PlateID, i_Subsample, o_rLocation)

    def GetNumberOfAnalogChannels(self, i_PlateID):
        return _CoreClient3.VClient_GetNumberOfAnalogChannels(self, i_PlateID)

    def GetAnalogChannelVoltage(self, i_PlateID, i_ZeroIndexedChannelIndex):
        return _CoreClient3.VClient_GetAnalogChannelVoltage(self, i_PlateID, i_ZeroIndexedChannelIndex)

    def GetAnalogChannelVoltageAtSample(self, i_PlateID, i_ZeroIndexedChannelIndex, i_Subsample):
        return _CoreClient3.VClient_GetAnalogChannelVoltageAtSample(self, i_PlateID, i_ZeroIndexedChannelIndex, i_Subsample)

    def GetEyeTrackerCount(self):
        return _CoreClient3.VClient_GetEyeTrackerCount(self)

    def GetEyeTrackerID(self, i_EyeTrackerIndex):
        return _CoreClient3.VClient_GetEyeTrackerID(self, i_EyeTrackerIndex)

    def GetEyeTrackerGlobalPosition(self, i_EyeTrackerID, o_rThreeVector):
        return _CoreClient3.VClient_GetEyeTrackerGlobalPosition(self, i_EyeTrackerID, o_rThreeVector)

    def GetEyeTrackerGlobalGazeVector(self, i_EyeTrackerID, o_rThreeVector):
        return _CoreClient3.VClient_GetEyeTrackerGlobalGazeVector(self, i_EyeTrackerID, o_rThreeVector)

    def GetCameraCount(self):
        return _CoreClient3.VClient_GetCameraCount(self)

    def GetCameraName(self, i_CameraIndex):
        return _CoreClient3.VClient_GetCameraName(self, i_CameraIndex)

    def GetCameraID(self, i_rCameraName):
        return _CoreClient3.VClient_GetCameraID(self, i_rCameraName)

    def GetCameraUserID(self, i_rCameraName):
        return _CoreClient3.VClient_GetCameraUserID(self, i_rCameraName)

    def GetCameraType(self, i_rCameraName):
        return _CoreClient3.VClient_GetCameraType(self, i_rCameraName)

    def GetCameraDisplayName(self, i_rCameraName):
        return _CoreClient3.VClient_GetCameraDisplayName(self, i_rCameraName)

    def GetCameraResolution(self, i_rCameraName):
        return _CoreClient3.VClient_GetCameraResolution(self, i_rCameraName)

    def GetIsVideoCamera(self, i_rCameraName):
        return _CoreClient3.VClient_GetIsVideoCamera(self, i_rCameraName)

    def GetCentroidCount(self, i_rCameraName):
        return _CoreClient3.VClient_GetCentroidCount(self, i_rCameraName)

    def GetCentroidPosition(self, i_rCameraName, i_CentroidIndex, o_rPosition):
        return _CoreClient3.VClient_GetCentroidPosition(self, i_rCameraName, i_CentroidIndex, o_rPosition)

    def GetCentroidWeight(self, i_rCameraName, i_CentroidIndex):
        return _CoreClient3.VClient_GetCentroidWeight(self, i_rCameraName, i_CentroidIndex)

    def GetGreyscaleBlobCount(self, i_rCameraName):
        return _CoreClient3.VClient_GetGreyscaleBlobCount(self, i_rCameraName)

    def GetGreyscaleBlob(self, i_rCameraName, i_BlobIndex, o_rLineXPositions, o_rLineYPositions, o_rLinePixelValues):
        return _CoreClient3.VClient_GetGreyscaleBlob(self, i_rCameraName, i_BlobIndex, o_rLineXPositions, o_rLineYPositions, o_rLinePixelValues)

    def GetVideoFrame(self, i_rCameraName, o_rVideoFramePtr):
        return _CoreClient3.VClient_GetVideoFrame(self, i_rCameraName, o_rVideoFramePtr)

    def SetCameraFilter(self, i_rCameraIdsForCentroids, i_rCameraIdsForBlobs, i_rCameraIdsForVideo):
        return _CoreClient3.VClient_SetCameraFilter(self, i_rCameraIdsForCentroids, i_rCameraIdsForBlobs, i_rCameraIdsForVideo)

    def ClearSubjectFilter(self):
        return _CoreClient3.VClient_ClearSubjectFilter(self)

    def AddToSubjectFilter(self, i_rSubjectName):
        return _CoreClient3.VClient_AddToSubjectFilter(self, i_rSubjectName)

    def LatestFrame(self):
        return _CoreClient3.VClient_LatestFrame(self)

    def CachedFrame(self):
        return _CoreClient3.VClient_CachedFrame(self)

    def SetTimingLog(self, i_rClientLog, i_rCGStreamLog):
        return _CoreClient3.VClient_SetTimingLog(self, i_rClientLog, i_rCGStreamLog)

    def ConfigureWireless(self):
        return _CoreClient3.VClient_ConfigureWireless(self)

    def NewClient(self):
        return _CoreClient3.VClient_NewClient(self)

# Register VClient in _CoreClient3:
_CoreClient3.VClient_swigregister(VClient)

class VRetimingClient(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, i_rClient):
        _CoreClient3.VRetimingClient_swiginit(self, _CoreClient3.new_VRetimingClient(i_rClient))
    __swig_destroy__ = _CoreClient3.delete_VRetimingClient

    def Connect(self, i_pClient, i_rHostName, i_bLightweight=False):
        return _CoreClient3.VRetimingClient_Connect(self, i_pClient, i_rHostName, i_bLightweight)

    def Disconnect(self):
        return _CoreClient3.VRetimingClient_Disconnect(self)

    def StartOutput(self, i_FrameRate):
        return _CoreClient3.VRetimingClient_StartOutput(self, i_FrameRate)

    def StopOutput(self):
        return _CoreClient3.VRetimingClient_StopOutput(self)

    def IsRunning(self):
        return _CoreClient3.VRetimingClient_IsRunning(self)

    def UpdateFrame(self, i_Offset):
        return _CoreClient3.VRetimingClient_UpdateFrame(self, i_Offset)

    def GetSubjectCount(self):
        return _CoreClient3.VRetimingClient_GetSubjectCount(self)

    def GetSubjectName(self, i_SubjectIndex):
        return _CoreClient3.VRetimingClient_GetSubjectName(self, i_SubjectIndex)

    def GetSubjectRootSegmentName(self, i_rSubjectName):
        return _CoreClient3.VRetimingClient_GetSubjectRootSegmentName(self, i_rSubjectName)

    def GetSegmentCount(self, i_rSubjectName):
        return _CoreClient3.VRetimingClient_GetSegmentCount(self, i_rSubjectName)

    def GetSegmentName(self, i_rSubjectName, i_SegmentIndex):
        return _CoreClient3.VRetimingClient_GetSegmentName(self, i_rSubjectName, i_SegmentIndex)

    def GetSegmentChildCount(self, i_rSubjectName, i_rSegmentName):
        return _CoreClient3.VRetimingClient_GetSegmentChildCount(self, i_rSubjectName, i_rSegmentName)

    def GetSegmentChildName(self, i_rSubjectName, i_rSegmentName, i_SegmentIndex):
        return _CoreClient3.VRetimingClient_GetSegmentChildName(self, i_rSubjectName, i_rSegmentName, i_SegmentIndex)

    def GetSegmentParentName(self, i_rSubjectName, i_rSegmentName):
        return _CoreClient3.VRetimingClient_GetSegmentParentName(self, i_rSubjectName, i_rSegmentName)

    def GetSegmentStaticTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentStaticTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentStaticRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentStaticRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentStaticRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation):
        return _CoreClient3.VRetimingClient_GetSegmentStaticRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation)

    def GetSegmentStaticRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector):
        return _CoreClient3.VRetimingClient_GetSegmentStaticRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector)

    def GetSegmentStaticRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentStaticRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentStaticScale(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentStaticScale(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentGlobalTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentGlobalTranslation(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentGlobalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentGlobalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentGlobalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation):
        return _CoreClient3.VRetimingClient_GetSegmentGlobalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation)

    def GetSegmentGlobalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector):
        return _CoreClient3.VRetimingClient_GetSegmentGlobalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector)

    def GetSegmentGlobalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentGlobalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentLocalTranslation(self, i_rSubjectName, i_rSegmentName, o_pThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentLocalTranslation(self, i_rSubjectName, i_rSegmentName, o_pThreeVector)

    def GetSegmentLocalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentLocalRotationHelical(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def GetSegmentLocalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation):
        return _CoreClient3.VRetimingClient_GetSegmentLocalRotationMatrix(self, i_rSubjectName, i_rSegmentName, o_rRotation)

    def GetSegmentLocalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector):
        return _CoreClient3.VRetimingClient_GetSegmentLocalRotationQuaternion(self, i_rSubjectName, i_rSegmentName, o_rFourVector)

    def GetSegmentLocalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector):
        return _CoreClient3.VRetimingClient_GetSegmentLocalRotationEulerXYZ(self, i_rSubjectName, i_rSegmentName, o_rThreeVector)

    def WaitForFrame(self):
        return _CoreClient3.VRetimingClient_WaitForFrame(self)

    def SetOutputLatency(self, i_OutputLatency):
        return _CoreClient3.VRetimingClient_SetOutputLatency(self, i_OutputLatency)

    def OutputLatency(self):
        return _CoreClient3.VRetimingClient_OutputLatency(self)

    def SetMaximumPrediction(self, i_MaxPrediction):
        return _CoreClient3.VRetimingClient_SetMaximumPrediction(self, i_MaxPrediction)

    def MaximumPrediction(self):
        return _CoreClient3.VRetimingClient_MaximumPrediction(self)

    def SetDebugLogFile(self, i_rLogFile):
        return _CoreClient3.VRetimingClient_SetDebugLogFile(self, i_rLogFile)

    def SetOutputFile(self, i_rLogFile):
        return _CoreClient3.VRetimingClient_SetOutputFile(self, i_rLogFile)

# Register VRetimingClient in _CoreClient3:
_CoreClient3.VRetimingClient_swigregister(VRetimingClient)



