function plot_order(px, py, pz)
    ax = gca;
    prev = [0, 0, 0];
    prev_i = 0;
%     for ii = 1:length(px)
%         if (px(ii) ~= prev(1)) || ...
%                 (py(ii) ~= prev(2)) || ...
%                 (pz(ii) ~= prev(3))
%             prev_i = prev_i + 1;
%             text(px(ii)+(ax.XLim(2)-ax.XLim(1))*0.01, ...
%                 py(ii)+(ax.YLim(2)-ax.YLim(1))*0.01, ...
%                 pz(ii)+(ax.ZLim(2)-ax.ZLim(1))*0.01, ...
%                 num2str(prev_i),'Color','k')
%             prev = [px(ii), py(ii), pz(ii)];
%         end
%     end
    plot3(px(1), py(1), pz(1), 'ko', ...
        'MarkerSize', 12, 'MarkerFaceColor', 'g')
    plot3(px(length(px)), py(length(px)), ...
        pz(length(px)), 'ko', ...
        'MarkerSize', 12, 'MarkerFaceColor', 'r')

end